version: '3'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: $MYSQL_PASS
      WORDPRESS_DB_NAME: wordpress
    tty: true
    ports:
      - 80:80
    volumes:
      - ./data/html:/var/www/html
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: $MYSQL_PASS
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    tty: true
    volumes:
      - ./data/mysql:/var/lib/mysql
    
